apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: comments-api
  namespace: monitoring
  labels:
    release: prometheus  # Este label é importante para o Prometheus Operator encontrar este ServiceMonitor
spec:
  selector:
    matchLabels:
      app: comments-api  # Este label deve corresponder ao label do seu Service
  endpoints:
  - port: http  # Este nome deve corresponder ao nome da porta no seu Service
    interval: 15s
    path: /metrics
  namespaceSelector:
    matchNames:
    - app  # Namespace onde sua aplicação está rodando 