apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: flask-app-monitor
  namespace: app
  labels:
    app: api-new-comments
spec:
  selector:
    matchLabels:
      app: api-new-comments
  endpoints:
    - port: http